name: CI

on:
  pull_request:
  push:
    paths-ignore:
      - "**/*.md"
      - "**/*.org"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 27.1
          - snapshot
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: actions/setup-python@v3.1.1
      - uses: conao3/setup-cask@master

      - uses: actions/checkout@v2.3.3
      - name: Install
        run: cask install
      - name: Test
        run: cask exec ert-runner
